### ISSUE TITLE
Clarify task 1

### ISSUE THREAD

**Issue by szarnyasg** [TransformationToolContest/ttc2018liveContest#11]
The specification of task 1 starts as follows:

> We consider a post as controversial, if it starts a debate through its comments. For this, we assign a 
score of 10 for each comment that belongs to a post. Hereby, we consider a comment belonging to a post, if it comments either the post itself or another comment that already belongs to the post. In addition, we also value if users liked comments, so we additionally assign a score of 1 for each user that has liked a comment. The score of a post then is the sum of 10 plus the amount of users that liked a comment over all comments that belong to the given post.

The last sentence is quite difficult to read. I think it should be interpreted as follows:
> The score of a post then is the sum of { 10 plus the amount of users that liked a comment over all comments that belong to the given post }.

However, this is still unclear about whether the user should be counted multiple times or not. For example, user1 liked two comments that belongs to a post, does this count as +1 or +2?
(Of course, this can be found out based on the tests results, but it would be worth clarifying the specifications.)

**Comment by georghinkel** [comment]
The score is computed per user per comment, so in your example that would be +2. But I agree that this could be clearer in the specification.

**Comment by agarciadom** [comment]
Can we touch up the spec accordingly, so we can close this issue?

**Comment by szarnyasg** [comment]
I think there is little value in patching the case description PDF of the live case - it was really intended for participants during STAF'18 and has limited relevance now. 
We'll definitely revise the case description in upcoming publications, and the comments above will hopefully assist in that. However, the issue can be closed for this repository.
