### ISSUE TITLE
XML parsing error in HawkSQLite-Q1 at size 512

### ISSUE THREAD

**Issue by marci543** [TransformationToolContest/ttc2018liveContest#112]
An XML parsing exception occured during the latest measurements (commit 18d10187768af04f2249a0142b340c02dc91a3c9).

`output/details/output/log-2021-05-13T13.55.19.log:5660` in the paper repo:
```Running benchmark: tool = HawkSQLite, change set = 512, query = Q1
Exception in thread "main" org.eclipse.emf.ecore.resource.Resource$IOWrappedException: Element type "posts" must be followed by either attribute specifications, ">" or "/>".
	at org.eclipse.emf.ecore.xmi.impl.XMLLoadImpl.load(XMLLoadImpl.java:195)
	at org.eclipse.emf.ecore.xmi.impl.XMLResourceImpl.doLoad(XMLResourceImpl.java:261)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1563)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1342)
	at org.hawk.ttc2018.BatchLauncher.applyChanges(BatchLauncher.java:70)
	at org.hawk.ttc2018.AbstractLauncher.applyChanges(AbstractLauncher.java:221)
	at org.hawk.ttc2018.AbstractLauncher.run(AbstractLauncher.java:137)
	at org.hawk.ttc2018.BatchLauncher.main(BatchLauncher.java:105)
Caused by: org.xml.sax.SAXParseExceptionpublicId: file:/ttc/models/512/initial.xmi; systemId: file:/ttc/models/512/initial.xmi; lineNumber: 402621; columnNumber: 32; Element type "posts" must be followed by either attribute specifications, ">" or "/>".
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
...
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.seekCloseOfStartTag(XMLDocumentFragmentScannerImpl.java:1394)
...
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
	at org.eclipse.emf.ecore.xmi.impl.XMLLoadImpl.load(XMLLoadImpl.java:175)
	... 7 more
```

It is strange, because other XMI-based tools run successfully before (L5557):
```
Running benchmark: tool = HawkNeo4JIncUpdateQuery, change set = 512, query = Q1
```

The image used in this benchmark is available as [`ftsrg/ttc2018@sha256:e3cf270aa36f895c70459b39c8d7afa97b634ea315fe6855913be36a524411ef`](https://hub.docker.com/layers/ftsrg/ttc2018/java8/images/sha256-e3cf270aa36f895c70459b39c8d7afa97b634ea315fe6855913be36a524411ef).

I ran it again. This time there were no errors but it reached the time limit.
With an increased time limit, I could run it (only this tool, size, query) successfully 5 times.

For comparison, the previous measurement also reached timeout for this:
`output/details/output-round-10/log-2021-05-09T18.30.46.log:5524` (commit cd5c9686f4810d425a33271d98c915dfb201ec2a):
```
Running benchmark: tool = HawkSQLite, change set = 512, query = Q1
Program reached the timeout set (600 s): tool = HawkSQLite, change set = 512, query = Q1, command: 'mvn -f ../Hawk/org.hawk.ttc2018/pom.xml -quiet -Pbatch -Dbackend=sqlite exec:exec'
```

I would suspect that a previous tool damaged the XMI file and the [restoration](https://github.com/TransformationToolContest/ttc2018liveContest/blob/ebb9bedc98d2c91842730a650aa8048d99df69c0/scripts/run.py#L103) was not complete, but the last run of that size finished on time.

**Comment by marci543** [comment]
I've rerun the benchmark and couldn't reproduce the issue.

**Comment by szarnyasg** [comment]
@bluezio did the Hawk SNAPSHOT change in the last few days?

**Comment by marci543** [comment]
I've used the same image without building it again.

**Comment by agarciadom** [comment]
The AbstractLauncher class in the Java solution already has a `finally` block that will restore a backup of the original file if there is an exception, no matter what. However, there is the possibility that the Python script could kill the process due to a timeout right while this is happening - this may corrupt the next run.

I think one way to solve this would be to simply never touch the `initial.xmi` file at all, and always work from a copy of it. Then it wouldn't matter if a previous process was killed in the middle of its processing.

I'll give it a stab ASAP and let you know when it's done :-). BTW, I noticed that in the paper the Hawk SQLite results appeared to be missing from some Q2 graphs - was there some other issue?

**Comment by agarciadom** [comment]
Actually, this approach doesn't work - the change XMI files refer to `initial.xmi`, so we have to work with that file. The other option is to do a backup the first time we use a particular `initial.xmi` file, and restore `initial.xmi` to that backup at the beginning of each run. That way, what happened in the previous run should not matter. I'll try that other approach.

**Comment by marci543** [comment]
> there is the possibility that the Python script could kill the process due to a timeout right while this is happening - this may corrupt the next run.

This should not be the problem since you've implemented a similar backup procedure in the `run.py` measurement script. But I don't have any idea what the problem might be.
https://github.com/TransformationToolContest/ttc2018liveContest/blob/ebb9bedc98d2c91842730a650aa8048d99df69c0/scripts/run.py#L101-L103

---
>BTW, I noticed that in the paper the Hawk SQLite results appeared to be missing from some Q2 graphs - was there some other issue?

There was no other issue. After the failed run of Q1, the other tools and queries weren't run. I've run them again separately. I think Artur has updated the diagrams, so it should be there now.

**Comment by agarciadom** [comment]
Right: I'm not sure what might be the problem then, either. I guess it wouldn't hurt to merge #113 anyway?

**Comment by marci543** [comment]
I agree. I checked that the names of the backup files differ so I wouldn't expect any conflict.
