### ISSUE TITLE
Differential datalog CI build fails

### ISSUE THREAD

**Issue by szarnyasg** [TransformationToolContest/ttc2018liveContest#118]
@qishen it seems the build is currently broken due to the `use of unstable library feature`. (Previously, this was masked by another CI bug in the build.)

https://github.com/TransformationToolContest/ttc2018liveContest/runs/6339663167?check_suite_focus=true#step:6:1386

```console
error[E0658]: use of unstable library feature 'available_parallelism'
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/dashmap-5.3.3/src/lib.rs:55:6
   |
55 |     (std::thread::available_parallelism().map_or(1, usize::from) * 4).next_power_of_two()
   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #74479 <https://github.com/rust-lang/rust/issues/74479> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `dashmap` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
Running benchmark with root directory /ttc
Building differential
Building differential-08
Building differential-datalog
Traceback (most recent call last):
  File "scripts/run.py", line 215, in <module>
    build(config, args.skip_tests and not args.test)
  File "scripts/run.py", line 41, in build
    subprocess.check_call(config.get('build', 'default'), shell=True)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ddlog/download.sh && DIFFERENTIAL_DATALOG_DISABLE_DEBUG= ./build.sh snq1 && DIFFERENTIAL_DATALOG_DISABLE_DEBUG= ./build.sh snq2' returned non-zero exit status 101.
The command '/bin/sh -c scripts/run.py -b' returned a non-zero code: 1
```

Could you please suggest a way / submit a PR to fix this? Do we have to use an unstable Rust version in the CI?

**Comment by qishen** [comment]
@szarnyasg Sorry for the delay I was very sick for a week and didn't notice the issue or email at all until now. I had the same problem too and it was resolved by using the nightly version of Rust because the stable version does not have the latest features used by DDLog.

**Comment by szarnyasg** [comment]
No problem, hope you're better now!

Could you please send a PR for the differential Dockerfile to make it use the nightly Rust build?

https://github.com/TransformationToolContest/ttc2018liveContest/blob/master/docker/Dockerfile-differential
