### ISSUE TITLE
Surprising results of reference solution

### ISSUE THREAD

**Issue by ValentinBesnard** [TransformationToolContest/ttc2018liveContest#2]
Hello,

I have run the reference solution but I obtain some surprising results.
For instance, for the initial model 1, the query Q1 gives "1039993|1048874|1039994".
By checking in the XMI file, we can notice that post with id = 1039993 has neither comments nor likes, so its score must be zero. It is the same for post 1048874 and post 1039994.
By the way, these three posts are the three first in the XMI file.
Maybe, you take the three posts with the least important score (or something like that)? Can you check to the reference solution if you see such an error?

Regards,

Valentin Besnard

**Comment by georghinkel** [comment]
Thanks, that is indeed wrong in the reference solution that so far also did not break ties by timestamps as required in the paper. I just corrected the solution.
