### ISSUE TITLE
Explicit (:Comment)-[:post]->(:Post) edge

### ISSUE THREAD

**Issue by szarnyasg** [TransformationToolContest/ttc2018liveContest#20]
The metamodel in the specification defines an explicit `post` edge that points from a `Comment` to the root `Post` of the `Submission` tree.

![image](https://user-images.githubusercontent.com/1402801/53509806-e31b7180-3abc-11e9-8c2d-1f0b155b0bd0.png)

Is it guaranteed that this edge is correct? If so, this makes the solution of _Task 1_ in both VIATRA and SQL (#17) simpler. VIATRA indexes the model so edges can be traversed both ways, and SQL joins eliminate any direction of an edge. Therefore, they no longer require computing transitive reachability on `Comment`s in the `Submission` tree.

I checked what the Xtend solution does: interestingly, it also avoids calculating transitive closure by iterating over the contained objects of the `Post`. The `Comment`s are contained through the `(:Submission)-[:commented]->(:Comment)` edges.

https://github.com/TransformationToolContest/ttc2018liveContest/blob/259eba4f5bf18f9283544b3d51c29788afd8f3ba/solutions/EMFSolutionXtend/src/ttc2018/SolutionQ1.xtend#L56-L65

**Comment by agarciadom** [comment]
I would assume so. @georghinkel, can you confirm?

**Comment by georghinkel** [comment]
Sorry for the late answer, yes, you can assume that this reference is correct.

**Comment by szarnyasg** [comment]
Cool, thanks!
