### ISSUE TITLE
Can not apply changes because of forward reference

### ISSUE THREAD

**Issue by rene-schoene** [TransformationToolContest/ttc2018liveContest#3]
Maybe I'm missing something, but it seems, that some of the change sequences have changes, which refer to elements that will be added by a future change.
Thus, I cannot apply changes in the given order.

An example is right in the first `models/1/change01,xmi`:
The first change references the `addedElement` of the next change.

How can that be resolved?
Should all the new elements be created upfront, such that they can be referred to before they are actually added to a list?

**Comment by agarciadom** [comment]
I would suggest doing so, yes. My Hawk solution is essentially doing that :-).

**Comment by georghinkel** [comment]
The thing is that the change sequences are simply recordings of operations and yes, the post has been added to the submissions of a user before adding it to the posts collection which is the containment.

So yes, you'd need to create these elements upfront, sorry.

**Comment by rene-schoene** [comment]
Hm, good to know. However, no time left.
I'll submit a solution only for the initial model then.
