### ISSUE TITLE
Revise loadExt.sh

### ISSUE THREAD

**Issue by szarnyasg** [TransformationToolContest/ttc2018liveContest#46]
https://github.com/TransformationToolContest/ttc2018liveContest/commits/master/solutions/SQLSolution/load-scripts/loadExt.sh

**Comment by agarciadom** [comment]
Could you provide a bit more detail? Not sure what are you reporting here :-).

**Comment by szarnyasg** [comment]
Yes, sorry for the lack of details! The current file has @arturboronat 's file system hard-coded.

https://github.com/TransformationToolContest/ttc2018liveContest/blob/c839ff3fed917a3b9d3192fc9296717de0a26994/solutions/SQLSolution/load-scripts/loadExt.sh#L1-L7

**Comment by agarciadom** [comment]
Fixed in MR #47.
