### ISSUE TITLE
Hawk dependencies cannot be installed on Java 11

### ISSUE THREAD

**Issue by szarnyasg** [TransformationToolContest/ttc2018liveContest#50]
@bluezio `./install-hawk-deps.sh` fails on Java 11 with `package javax.annotation does not exist`. Is it possible to build Hawk with Java 11? If not, it's clearly not possible to migrate all projects to this version.

**Comment by agarciadom** [comment]
I do intend to look at this - just didn't have time to get to it :-D. Reopening.
