### ISSUE TITLE
Java versions

### ISSUE THREAD

**Issue by szarnyasg** [TransformationToolContest/ttc2018liveContest#51]
Followup of issues #40 and #50.

I am trying to collect the required Java versions:

* `differential*`: 8/11
* `EMFSolutionAOF`: 8 
* `EMFSolutionATL*`: 8
* `EMFSolutionViatra`: 8/11?
* `EMFSolutionXtend`: 8/11
* `EMFSolutionYAMTL*`: 11 (!)
* `Hawk*`: 8/11
* `GraphBLAS`: 8/11
* `jastadd-ttc18*`: 8
* `Naiad*`: -
* `Neo4j*`: 8 (might work with 11 but not officially supported)
* `NMF*`: -
* `SQLSolution*`: 8/11

**Comment by szarnyasg** [comment]
Okay, so it seems Java version 8 is _almost_ the common denominator with the exception of `EMFSolutionYAMTL`. I've downgraded it from "11" to "1.8", see #53.

**Comment by agarciadom** [comment]
Hawk works with 11 now: it was only missing a dependency on javax.annotation, which was dropped from Java 11 onwards as it was considered a Java EE API.

**Comment by szarnyasg** [comment]
Cool, I've amended the list above! Thanks.

**Comment by szarnyasg** [comment]
This is issue is no longer a problem due to the dockerization performed in #69.
