### ISSUE TITLE
HawkSQLite* tools don't produce any output

### ISSUE THREAD

**Issue by marci543** [TransformationToolContest/ttc2018liveContest#99]
After the measurements it looks like HawkSQLite* tools don't produce measurement results on STDOUT.
The result check in run.py currently only looks for wrong results, not the absence of results.

**Comment by agarciadom** [comment]
That is quite odd - I was obtaining results with ` scripts/run.py -bm`  just fine for SQLite. Could you clarify what is the command you are running to obtain the results? I assume you are using the Java 8 Docker image?

**Comment by marci543** [comment]
I tried the following.
```bash
echo '{"Queries":["Q1"],"Tools":["HawkIncUpdateQuery","HawkSQLite"],"ChangeSets":["1"],"Sequences":20,"Runs":1,"Timeout":1800}' > config/config-docker-java8.json
./docker.sh --pull -r -t java8
cat output/output-docker-*.csv
grep HawkSQLite output/output-docker-*.csv
```
Docker Hub stores a quite fresh image (5ab3cbbce2f4200254cda34f28e39e63055407c6). (Check last step [here](https://hub.docker.com/layers/ftsrg/ttc2018/java8/images/sha256-eb7217f4f49a6005e3a80374973571a8cadcd6f748962d994138ce468f330cbc?context=explore) or `docker run --rm ftsrg/ttc2018:java8 cat README.md`)

**Comment by agarciadom** [comment]
Thanks, will try it out later!

**Comment by agarciadom** [comment]
Oops, it seems the SQLite backend requires Java 9 or newer, because I was using InputStream.transferTo (which is new in Java 9). I'll see if I can find a Java 8 equivalent for it - it's probably the easiest way to solve the issue at the moment.

**Comment by marci543** [comment]
Or you can move this part of the code to the Java11 image if separable.
My other concern is the lack of any error message.

**Comment by agarciadom** [comment]
I've got an MR with the fix, waiting for the pipeline to pass:

https://gitlab.com/hawklabs/hawk-sqlite/-/merge_requests/1

The error message is logged into the hawk.log file in Hawk: in fact, the way I got the error message about that problem in the backend was running the same `scripts/run.py -mc` command from inside the Docker image and reading that log. Getting the exception to bubble out the normal way would require some major changes in the internal Hawk APIs at the moment, I'm afraid, which would also break existing UI/API clients. (Well, or I could turn all those SQLExceptions into runtime exceptions, but that feels even worse...)

**Comment by agarciadom** [comment]
MR1 passed in the SQLite backend, now we only need this other pipeline to pass and we'll have Maven artifacts with the fix:

https://gitlab.com/hawklabs/hawk-sqlite/-/pipelines/297271834

**Comment by agarciadom** [comment]
Ah, silly me - I realize that for cases like this, I should just be letting the solution crash instead of catching and logging all remaining exceptions in their main method :-). Let me fix that as well in an MR.

**Comment by agarciadom** [comment]
OK, the hawk-sqlite backend now has Maven artefacts that work in Java 8 (I tried running all tests with a local Java 8 installation), and I have created an MR (#100) so Hawk won't simply silently log these problems in the hawk.log file anymore.

Feel free to merge #100 when the CI passes for it, and then all the comments in this issue should have been addressed.

**Comment by agarciadom** [comment]
#100 has been merged. Please try to rerun the SQLite experiments when the images are updated.

**Comment by marci543** [comment]
I've run the commands from above and it produces output.
Thanks for the fix.
